source 'https://github.com/louistran99/podspecs.git'
platform :ios, '12.0'
use_frameworks!

target 'MyPodName_Example' do
  pod 'MyPodName', :path => '../'
  
  target 'MyPodName_Tests' do
    inherit! :search_paths

    
  end
end
