platform :ios, '12.0'
use_frameworks!

target 'MyPodName_Example' do
  pod 'Alamofire', '~> 4.7'
  pod 'MyPodName', :path => '../'
  
  target 'MyPodName_Tests' do
    inherit! :search_paths

    
  end
end
